#!/bin/ruby

# Tom Trebisky  5-12-2018

# Anyone who realizes what is being done here will be appalled.
# I am launching a process to run objdump for EACH and EVERY line
# that needs to be disassembled.  Too bad.
# If you don't like it, write your own disassembler !!  :-)
# This is a "get 'er done" approach and enabled me to get most
# of this written in an evening.  Besides that, it takes
# less than 10 seconds to run on my 3.5 Ghz x86_64 system,
# and that computer has nothing better to do.

# I have discovered that rom1 follows after rom0 at
# addresses 0x40060000 to 0x4006ffff
# So we actually have 7 * 64k of ROM to deal with.
#    458752 bytes

# After chasing the thread of execution that begins at
# 0x40000400, we have disassembled 19234 bytes of 458752
# (approximately 4 percent!)

# TODO:
# 1 - find out why my "Twice" messages don't run in a continuous
#       flow thru areas where I am sure they must.  DONE
#  Things involving setting ruby subarrays that I still don't understand.
# 2 - deal with l32r nicely
# 3 - generate an output in proper order
#  (this will need to become a 2 pass thing of some kind)
# 4 - dump the "gaps" in some nice way.
# 5 - symbols from ld file
# 6 - strings
# 7 - add call table and generate "sub_xxx" sort of labels
#   for all call targets not in the ld file.

$bin_file = "esp32.bin"
$elf_file = "esp32.elf"
$rom_base = 0x40000000
$rom_size = 65536 * 7

def error ( a, s )
    print "Trouble at 0x%08x\n" % a
    puts s
    exit
end

# Information for a single instruction
class Instr
    attr_reader :addr
    attr_reader :line
    attr_reader :size
    attr_reader :target
    attr_reader :is_branch
    attr_reader :is_call
    attr_reader :is_jump
    attr_reader :is_l32r
    attr_reader :is_term

    def initialize ( addr, stuff )
	@is_branch = false
	@is_call = false
	@is_jump = false
	@is_l32r = false
	@is_term = false
	@target = nil

	@addr = addr

	info = stuff.split "\n"
#	puts stuff
#	puts info.size
	line = nil
	match = Regexp.new "^%08x:" % addr
	info.each { |l|
	    line = l if match =~ l
	}

	error addr, stuff unless line

	@line = line
	w = line.split
	if w.size < 3
	    error addr, stuff
	end
	@size = w[1].size / 2
	if @size < 1 or @size > 3
	    error addr, stuff
	end
	op = w[2]
	@is_term = true if op =~ /^ret/
	@is_term = true if op =~ /^j/
	@is_jump = true if op =~ /^j/
	@is_jump = false if op =~ /^jx/
	@is_branch = true if op =~ /^loopnez/
	@is_branch = true if op =~ /^b/
	@is_branch = false if op =~ /^break/
	@is_call = true if op =~ /^call/
	@is_call = false if op =~ /^callx/
	@is_l32r = true if op =~ /^l32r/
	if @is_jump
	    #puts "Jump to #{w[3]}"
	    @target = w[3]
	end
	if @is_call
	    @target = w[3]
	end
	if @is_branch
	    @target = w[-1]
	end
	if @is_l32r
	    @target = w[-1]
	end
    end
end

class Dumper
    def initialize
	@elf = $elf_file
	@size = $rom_size
	@base = $rom_base

	@show_pass1 = true
	@debug_pass1 = true

	# We need this to fetch stuff for l32r cleanup
	file = File.open $bin_file, "rb"
	@binary = file.read
	file.close
	if @binary.size != $rom_size
	    puts "Something is wrong with binary file"
	    exit
	end

	@limit = @base + @size -1
	# This should be on the search path, if not prefix
	# with something like /opt/esp32/xtensa-esp32-elf/bin
#	@cmd = "xtensa-lx106-elf-objdump -mxtensa -d -z"
	@cmd = "xtensa-esp32-elf-objdump -mxtensa -d -z"
	@cur_addr = Array.new
	@old_addr = Array.new
	@map = Array.new @size, "X"
    end
    def one_inst ( addr )
#        $(OBJDUMP) --start-address=0x40000000 --stop-address=0x400003ff rom0.elf >zzz.dis
	start = "0x%08x" % addr
	eaddr = addr + 3
	stop = "0x%08x" % eaddr
	range = "--start-address=#{start} --stop-address=#{stop}"
	cmd = @cmd + " " + range + " #{@elf}"
#	puts cmd
	return Instr.new addr, `#{cmd}`
    end
    def add_addr ( target )
	#puts "Check add: " + target
	error 0xdead, target if target !~ /^0x4/
	addr = target.hex
	#puts "Maybe add: %08x" % addr
	# Never see Wow, now that we have all 7 * 64k
	if addr > @limit
	    puts "Wow, skipping: %08x" % addr
	    return
	end
	return if @new_addr.include? addr
	return if @old_addr.include? addr
	puts "Add: %08x" % addr if @debug_pass1
	@new_addr << addr
    end

    def claim ( index, size, type )
	size.times {
	    @map[index] = type
	    index += 1
	}
    end
    def fetch_long ( index )
	bytes = @binary[index,4]
	vals = bytes.unpack "L"
	val = vals[0]
    end

    def get_l32r ( addr )
	val = fetch_long addr - @base
	return "0x%08x" % val
    end

    def print_inst ( i )
	    if i.is_l32r
		val = get_l32r ( i.target.hex )
		puts i.line + "\t; ( " + val + " )"
	    else
		puts i.line
	    end
    end

    def range1 ( addr )
	loop {
	    i = one_inst addr

	    print_inst i if @show_pass1

	    if i.is_l32r
		claim (i.target.hex - @base), 4, "L"
	    end

	    index = addr - @base

	    # This indicates we have "slid" into a section we
	    # already disassembled, usually because we followed a
	    # branch prior to that section, so we can justend.
	    if @map[index] == "I"
		# print "Twice visiting: %08x\n" % addr
		puts "*** END (Twice) ***" if @debug_pass1
		break
	    end

	    claim index, i.size, "I"

	    add_addr i.target if i.is_jump
	    add_addr i.target if i.is_branch
	    add_addr i.target if i.is_call
	    addr += i.size
	    if i.is_term
		puts "*** END ***" if @debug_pass1
		break
	    end
	    i = nil	# help garbage collection ??
	}
    end
    def pass1 ( addr )
	@cur_addr << addr
	pass = 0
	loop {
	    pass += 1
	    break if @cur_addr.size < 1
	    puts "Starting pass for %d items" % @cur_addr.size if @debug_pass1
	    @new_addr = Array.new
	    loop {
		t = @cur_addr.shift
		break unless t
		t_hex = "%08x" % t
		@old_addr << t
		next if @map[t-@base] != "X"
		puts "Chase: " + t_hex + " (#{@cur_addr.size})" if @debug_pass1
		range1 t
	    }
	    puts "!!! Pass #{pass} finished, %d waiting" % @new_addr.size if @debug_pass1

	    # We drop things that we had branches to, but were
	    # in the range we continued to disassemble.
	    @new_addr.each { |n|
		if @map[n-@base] != "X"
		    puts "Dropping: %08x" % n if @debug_pass1
		    next
		end
		@cur_addr << n
	    }
	}
    end

    # The game here is to collect contiguous blocks of the same type
    def get_range ( index )
	if index >= @size
	    return "Q", 0
	end
	if @map[index] == "L"
	    return "L", index + 4
	end
	t = @map[index]
	loop {
	    index = index + 1
	    break if index >= @size
	    break if @map[index] != t
	}
	return t, index
    end

    # Just display, following a linear thread of execution
    # until it terminates.
    def range2 ( addr )
	loop {
	    i = one_inst addr
	    print_inst i

	    addr += i.size
	    if i.is_term
		# puts "*** END2 ***"
		break
	    end
	    i = nil	# help garbage collection ??
	}
	return addr
    end
    def pass2
	index = 0
	loop {
	    type, nxt = get_range index
	    break if type == "Q"
	    addr = @base + index
	    addr_hex = "%08x" % addr
	    xaddr = @base + nxt
	    xaddr_hex = "%08x" % xaddr
	    eaddr = xaddr - 1
	    eaddr_hex = "%08x" % eaddr
	    
	    puts "Pass2 #{addr_hex} #{xaddr_hex} #{type}"

	    # Handle a l32r
	    if type == "L"
		hval = "%08x" % fetch_long(index)
		print "#{addr_hex}:	" + hval + "	; l32r\n"
	    elsif type == "I"
		loop {
		    addr_hex = "%08x" % addr
		    naddr = range2 addr
		    nhex = "%08x" % naddr
		    puts "Range2 #{addr_hex} #{nhex}"
		    break if naddr >= xaddr
		    #print "I ended prematurely: #{nhex} #{xaddr_hex}\n"

		    addr = naddr
		}
	    else
		print "#{addr_hex} to #{eaddr_hex}  --------- Unknown territory !!!\n"
	    end
	    index = nxt
	}
    end
    def show_map
	addr = @base
	i = 0
	loop {
	    break unless @map[i]
	    addr_hex = "%08x" % addr
	    print "MAP #{addr_hex}: "
	    16.times {
		print " " + @map[i] 
		i += 1
	    }
	    print "\n"
	    addr += 16
	}
    end
    def summary
	count = 0;
	@map.each { |m|
	    count += 1 if m != "X"
	}
	puts "disassembled #{count} bytes of #{@size}"
    end
end

d = Dumper.new

d.pass1 0x40000400
puts "End of Pass 1"
d.show_map
d.pass2
d.summary

#puts "DONE"

# THE END

